// autogenerated by ServerDbGenerator
#pragma warning disable IDE1006 // Naming Styles
#pragma warning disable IDE0017 // Object Initialization
#pragma warning disable IDE0028 // Collection Initialization
#pragma warning disable CS1998 // Async method lacks 'await' operators and will run synchronously
#pragma warning disable CS0105 // Using directive appeared previously in this namespace
#pragma warning disable CS0612 // Type or member is obsolete
using crosscutting;
using crosscutting.sql;
using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using System.Threading.Tasks;
using System.Linq;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using crosscutting.cqrs;
namespace test.sql
{
	using test.sql;
	using test.model;
	using test.model;
	using test.model;
	using test.model;
// generated class, do not modify, source here: file:///placeholder
public partial class tstTestDBContext : tstITestDBContext
{
	IQueryable<tstIRawDbEntity> tstITestDBContext.Raws => Raws;
	IEnumerable<tstIRawDbEntity> tstITestDBContext.RawsLocal => RawsLocal;
	IInMemoryDBSet<tstIRawDbEntity, tstRaw> tstITestDBContext.RawsInMemory => null;
	IQueryable<tstIRequiredSharedRefDbEntity> tstITestDBContext.RequiredSharedRefs => RequiredSharedRefs;
	IEnumerable<tstIRequiredSharedRefDbEntity> tstITestDBContext.RequiredSharedRefsLocal => RequiredSharedRefsLocal;
	IInMemoryDBSet<tstIRequiredSharedRefDbEntity, tstRequiredSharedRef> tstITestDBContext.RequiredSharedRefsInMemory => null;
	IQueryable<tstIOptionalSharedRefDbEntity> tstITestDBContext.OptionalSharedRefs => OptionalSharedRefs;
	IEnumerable<tstIOptionalSharedRefDbEntity> tstITestDBContext.OptionalSharedRefsLocal => OptionalSharedRefsLocal;
	IInMemoryDBSet<tstIOptionalSharedRefDbEntity, tstOptionalSharedRef> tstITestDBContext.OptionalSharedRefsInMemory => null;
	IQueryable<tstICompositeRefParentDbEntity> tstITestDBContext.CompositeRefParents => CompositeRefParents;
	IEnumerable<tstICompositeRefParentDbEntity> tstITestDBContext.CompositeRefParentsLocal => CompositeRefParentsLocal;
	IInMemoryDBSet<tstICompositeRefParentDbEntity, tstCompositeRefParent> tstITestDBContext.CompositeRefParentsInMemory => null;
	IQueryable<tstIOptionalCompositeRefParentDbEntity> tstITestDBContext.OptionalCompositeRefParents => OptionalCompositeRefParents;
	IEnumerable<tstIOptionalCompositeRefParentDbEntity> tstITestDBContext.OptionalCompositeRefParentsLocal => OptionalCompositeRefParentsLocal;
	IInMemoryDBSet<tstIOptionalCompositeRefParentDbEntity, tstOptionalCompositeRefParent> tstITestDBContext.OptionalCompositeRefParentsInMemory => null;
	IQueryable<tstIOwnerContainerDbEntity> tstITestDBContext.OwnerContainers => OwnerContainers;
	IEnumerable<tstIOwnerContainerDbEntity> tstITestDBContext.OwnerContainersLocal => OwnerContainersLocal;
	IInMemoryDBSet<tstIOwnerContainerDbEntity, tstOwnerContainer> tstITestDBContext.OwnerContainersInMemory => null;
	IQueryable<tstICompositesContainerDbEntity> tstITestDBContext.CompositesContainers => CompositesContainers;
	IEnumerable<tstICompositesContainerDbEntity> tstITestDBContext.CompositesContainersLocal => CompositesContainersLocal;
	IInMemoryDBSet<tstICompositesContainerDbEntity, tstCompositesContainer> tstITestDBContext.CompositesContainersInMemory => null;
	IQueryable<tstISharedContainerDbEntity> tstITestDBContext.SharedContainers => SharedContainers;
	IEnumerable<tstISharedContainerDbEntity> tstITestDBContext.SharedContainersLocal => SharedContainersLocal;
	IInMemoryDBSet<tstISharedContainerDbEntity, tstSharedContainer> tstITestDBContext.SharedContainersInMemory => null;
	IQueryable<tstIMultipleSharedContainerDbEntity> tstITestDBContext.MultipleSharedContainers => MultipleSharedContainers;
	IEnumerable<tstIMultipleSharedContainerDbEntity> tstITestDBContext.MultipleSharedContainersLocal => MultipleSharedContainersLocal;
	IInMemoryDBSet<tstIMultipleSharedContainerDbEntity, tstMultipleSharedContainer> tstITestDBContext.MultipleSharedContainersInMemory => null;
	IQueryable<tstIMixedContainerDbEntity> tstITestDBContext.MixedContainers => MixedContainers;
	IEnumerable<tstIMixedContainerDbEntity> tstITestDBContext.MixedContainersLocal => MixedContainersLocal;
	IInMemoryDBSet<tstIMixedContainerDbEntity, tstMixedContainer> tstITestDBContext.MixedContainersInMemory => null;
	IQueryable<tstIMultipleCompositeRefDbEntity> tstITestDBContext.MultipleCompositeRefs => MultipleCompositeRefs;
	IEnumerable<tstIMultipleCompositeRefDbEntity> tstITestDBContext.MultipleCompositeRefsLocal => MultipleCompositeRefsLocal;
	IInMemoryDBSet<tstIMultipleCompositeRefDbEntity, tstMultipleCompositeRef> tstITestDBContext.MultipleCompositeRefsInMemory => null;
	IQueryable<tstIMultipleSharedRefDbEntity> tstITestDBContext.MultipleSharedRefs => MultipleSharedRefs;
	IEnumerable<tstIMultipleSharedRefDbEntity> tstITestDBContext.MultipleSharedRefsLocal => MultipleSharedRefsLocal;
	IInMemoryDBSet<tstIMultipleSharedRefDbEntity, tstMultipleSharedRef> tstITestDBContext.MultipleSharedRefsInMemory => null;
	IQueryable<tstINestedCompositeRootDbEntity> tstITestDBContext.NestedCompositeRoots => NestedCompositeRoots;
	IEnumerable<tstINestedCompositeRootDbEntity> tstITestDBContext.NestedCompositeRootsLocal => NestedCompositeRootsLocal;
	IInMemoryDBSet<tstINestedCompositeRootDbEntity, tstNestedCompositeRoot> tstITestDBContext.NestedCompositeRootsInMemory => null;
	IQueryable<tstIChildDbEntity> tstITestDBContext.Children => Children;
	IEnumerable<tstIChildDbEntity> tstITestDBContext.ChildrenLocal => ChildrenLocal;
	IInMemoryDBSet<tstIChildDbEntity, tstChild> tstITestDBContext.ChildrenInMemory => null;
	IQueryable<tstIParentDbEntity> tstITestDBContext.Parents => Parents;
	IEnumerable<tstIParentDbEntity> tstITestDBContext.ParentsLocal => ParentsLocal;
	IInMemoryDBSet<tstIParentDbEntity, tstParent> tstITestDBContext.ParentsInMemory => null;
	IQueryable<tstIT001ChildDbEntity> tstITestDBContext.T001Children => T001Children;
	IEnumerable<tstIT001ChildDbEntity> tstITestDBContext.T001ChildrenLocal => T001ChildrenLocal;
	IInMemoryDBSet<tstIT001ChildDbEntity, tstT001Child> tstITestDBContext.T001ChildrenInMemory => null;
	IQueryable<tstIT001ParentOwnerDbEntity> tstITestDBContext.T001ParentOwners => T001ParentOwners;
	IEnumerable<tstIT001ParentOwnerDbEntity> tstITestDBContext.T001ParentOwnersLocal => T001ParentOwnersLocal;
	IInMemoryDBSet<tstIT001ParentOwnerDbEntity, tstT001ParentOwner> tstITestDBContext.T001ParentOwnersInMemory => null;
	IQueryable<tstIParentWithSharedListDbEntity> tstITestDBContext.ParentWithSharedLists => ParentWithSharedLists;
	IEnumerable<tstIParentWithSharedListDbEntity> tstITestDBContext.ParentWithSharedListsLocal => ParentWithSharedListsLocal;
	IInMemoryDBSet<tstIParentWithSharedListDbEntity, tstParentWithSharedList> tstITestDBContext.ParentWithSharedListsInMemory => null;
	IQueryable<tstIT002ChildDbEntity> tstITestDBContext.T002Children => T002Children;
	IEnumerable<tstIT002ChildDbEntity> tstITestDBContext.T002ChildrenLocal => T002ChildrenLocal;
	IInMemoryDBSet<tstIT002ChildDbEntity, tstT002Child> tstITestDBContext.T002ChildrenInMemory => null;
	IQueryable<tstIT002ParentOwnerDbEntity> tstITestDBContext.T002ParentOwners => T002ParentOwners;
	IEnumerable<tstIT002ParentOwnerDbEntity> tstITestDBContext.T002ParentOwnersLocal => T002ParentOwnersLocal;
	IInMemoryDBSet<tstIT002ParentOwnerDbEntity, tstT002ParentOwner> tstITestDBContext.T002ParentOwnersInMemory => null;
	IQueryable<tstIT002ChildHolderDbEntity> tstITestDBContext.T002ChildHolders => T002ChildHolders;
	IEnumerable<tstIT002ChildHolderDbEntity> tstITestDBContext.T002ChildHoldersLocal => T002ChildHoldersLocal;
	IInMemoryDBSet<tstIT002ChildHolderDbEntity, tstT002ChildHolder> tstITestDBContext.T002ChildHoldersInMemory => null;
	IQueryable<tstIT003ChildDbEntity> tstITestDBContext.T003Children => T003Children;
	IEnumerable<tstIT003ChildDbEntity> tstITestDBContext.T003ChildrenLocal => T003ChildrenLocal;
	IInMemoryDBSet<tstIT003ChildDbEntity, tstT003Child> tstITestDBContext.T003ChildrenInMemory => null;
	IQueryable<tstIT003ParentOwnerDbEntity> tstITestDBContext.T003ParentOwners => T003ParentOwners;
	IEnumerable<tstIT003ParentOwnerDbEntity> tstITestDBContext.T003ParentOwnersLocal => T003ParentOwnersLocal;
	IInMemoryDBSet<tstIT003ParentOwnerDbEntity, tstT003ParentOwner> tstITestDBContext.T003ParentOwnersInMemory => null;
	IQueryable<tstIT003ChildHolderDbEntity> tstITestDBContext.T003ChildHolders => T003ChildHolders;
	IEnumerable<tstIT003ChildHolderDbEntity> tstITestDBContext.T003ChildHoldersLocal => T003ChildHoldersLocal;
	IInMemoryDBSet<tstIT003ChildHolderDbEntity, tstT003ChildHolder> tstITestDBContext.T003ChildHoldersInMemory => null;
	IQueryable<tstIT004RecursiveLinkSetDbEntity> tstITestDBContext.T004RecursiveLinkSets => T004RecursiveLinkSets;
	IEnumerable<tstIT004RecursiveLinkSetDbEntity> tstITestDBContext.T004RecursiveLinkSetsLocal => T004RecursiveLinkSetsLocal;
	IInMemoryDBSet<tstIT004RecursiveLinkSetDbEntity, tstT004RecursiveLinkSet> tstITestDBContext.T004RecursiveLinkSetsInMemory => null;
	IQueryable<tstIT005RecursiveLinkListDbEntity> tstITestDBContext.T005RecursiveLinkLists => T005RecursiveLinkLists;
	IEnumerable<tstIT005RecursiveLinkListDbEntity> tstITestDBContext.T005RecursiveLinkListsLocal => T005RecursiveLinkListsLocal;
	IInMemoryDBSet<tstIT005RecursiveLinkListDbEntity, tstT005RecursiveLinkList> tstITestDBContext.T005RecursiveLinkListsInMemory => null;
	IQueryable<tstIT006PerfMaxQueryItemDbEntity> tstITestDBContext.T006PerfMaxQueryItems => T006PerfMaxQueryItems;
	IEnumerable<tstIT006PerfMaxQueryItemDbEntity> tstITestDBContext.T006PerfMaxQueryItemsLocal => T006PerfMaxQueryItemsLocal;
	IInMemoryDBSet<tstIT006PerfMaxQueryItemDbEntity, tstT006PerfMaxQueryItem> tstITestDBContext.T006PerfMaxQueryItemsInMemory => null;
	IQueryable<tstIT006PerfMaxQueryValueDbEntity> tstITestDBContext.T006PerfMaxQueryValues => T006PerfMaxQueryValues;
	IEnumerable<tstIT006PerfMaxQueryValueDbEntity> tstITestDBContext.T006PerfMaxQueryValuesLocal => T006PerfMaxQueryValuesLocal;
	IInMemoryDBSet<tstIT006PerfMaxQueryValueDbEntity, tstT006PerfMaxQueryValue> tstITestDBContext.T006PerfMaxQueryValuesInMemory => null;
	IQueryable<tstIT007LeafDbEntity> tstITestDBContext.T007Leaves => T007Leaves;
	IEnumerable<tstIT007LeafDbEntity> tstITestDBContext.T007LeavesLocal => T007LeavesLocal;
	IInMemoryDBSet<tstIT007LeafDbEntity, tstT007Leaf> tstITestDBContext.T007LeavesInMemory => null;
	IQueryable<tstIT007RootDbEntity> tstITestDBContext.T007Roots => T007Roots;
	IEnumerable<tstIT007RootDbEntity> tstITestDBContext.T007RootsLocal => T007RootsLocal;
	IInMemoryDBSet<tstIT007RootDbEntity, tstT007Root> tstITestDBContext.T007RootsInMemory => null;
	IQueryable<tstIT008ParentDbEntity> tstITestDBContext.T008Parents => T008Parents;
	IEnumerable<tstIT008ParentDbEntity> tstITestDBContext.T008ParentsLocal => T008ParentsLocal;
	IInMemoryDBSet<tstIT008ParentDbEntity, tstT008Parent> tstITestDBContext.T008ParentsInMemory => null;
	IQueryable<tstIT009PrincipalDbEntity> tstITestDBContext.T009Principals => T009Principals;
	IEnumerable<tstIT009PrincipalDbEntity> tstITestDBContext.T009PrincipalsLocal => T009PrincipalsLocal;
	IInMemoryDBSet<tstIT009PrincipalDbEntity, tstT009Principal> tstITestDBContext.T009PrincipalsInMemory => null;
	IQueryable<tstIT009UserDbEntity> tstITestDBContext.T009Users => T009Users;
	IEnumerable<tstIT009UserDbEntity> tstITestDBContext.T009UsersLocal => T009UsersLocal;
	IInMemoryDBSet<tstIT009UserDbEntity, tstT009User> tstITestDBContext.T009UsersInMemory => null;
	IQueryable<tstIT010CompositeRefParentDbEntity> tstITestDBContext.T010CompositeRefParents => T010CompositeRefParents;
	IEnumerable<tstIT010CompositeRefParentDbEntity> tstITestDBContext.T010CompositeRefParentsLocal => T010CompositeRefParentsLocal;
	IInMemoryDBSet<tstIT010CompositeRefParentDbEntity, tstT010CompositeRefParent> tstITestDBContext.T010CompositeRefParentsInMemory => null;
	IQueryable<tstIT011CompositeRefParentDbEntity> tstITestDBContext.T011CompositeRefParents => T011CompositeRefParents;
	IEnumerable<tstIT011CompositeRefParentDbEntity> tstITestDBContext.T011CompositeRefParentsLocal => T011CompositeRefParentsLocal;
	IInMemoryDBSet<tstIT011CompositeRefParentDbEntity, tstT011CompositeRefParent> tstITestDBContext.T011CompositeRefParentsInMemory => null;
	IQueryable<tstIT012CompositeRefParentDbEntity> tstITestDBContext.T012CompositeRefParents => T012CompositeRefParents;
	IEnumerable<tstIT012CompositeRefParentDbEntity> tstITestDBContext.T012CompositeRefParentsLocal => T012CompositeRefParentsLocal;
	IInMemoryDBSet<tstIT012CompositeRefParentDbEntity, tstT012CompositeRefParent> tstITestDBContext.T012CompositeRefParentsInMemory => null;
	IQueryable<tstIT013CompositeRefParentDbEntity> tstITestDBContext.T013CompositeRefParents => T013CompositeRefParents;
	IEnumerable<tstIT013CompositeRefParentDbEntity> tstITestDBContext.T013CompositeRefParentsLocal => T013CompositeRefParentsLocal;
	IInMemoryDBSet<tstIT013CompositeRefParentDbEntity, tstT013CompositeRefParent> tstITestDBContext.T013CompositeRefParentsInMemory => null;
	IQueryable<tstIT014AutoCreateValueDbEntity> tstITestDBContext.T014AutoCreateValues => T014AutoCreateValues;
	IEnumerable<tstIT014AutoCreateValueDbEntity> tstITestDBContext.T014AutoCreateValuesLocal => T014AutoCreateValuesLocal;
	IInMemoryDBSet<tstIT014AutoCreateValueDbEntity, tstT014AutoCreateValue> tstITestDBContext.T014AutoCreateValuesInMemory => null;
	IQueryable<tstIT015ParentRecordDbRecord> tstITestDBContext.T015ParentRecords => T015ParentRecords;
	IEnumerable<tstIT015ParentRecordDbRecord> tstITestDBContext.T015ParentRecordsLocal => T015ParentRecordsLocal;
	IInMemoryDBSet<tstIT015ParentRecordDbRecord, tstT015ParentRecord> tstITestDBContext.T015ParentRecordsInMemory => null;
	IQueryable<tstIT015ChildL1RecordDbRecord> tstITestDBContext.T015ChildL1Records => T015ChildL1Records;
	IEnumerable<tstIT015ChildL1RecordDbRecord> tstITestDBContext.T015ChildL1RecordsLocal => T015ChildL1RecordsLocal;
	IInMemoryDBSet<tstIT015ChildL1RecordDbRecord, tstT015ChildL1Record> tstITestDBContext.T015ChildL1RecordsInMemory => null;
	IQueryable<tstIT015ChildL2RecordDbRecord> tstITestDBContext.T015ChildL2Records => T015ChildL2Records;
	IEnumerable<tstIT015ChildL2RecordDbRecord> tstITestDBContext.T015ChildL2RecordsLocal => T015ChildL2RecordsLocal;
	IInMemoryDBSet<tstIT015ChildL2RecordDbRecord, tstT015ChildL2Record> tstITestDBContext.T015ChildL2RecordsInMemory => null;
	IQueryable<tstIT015ChildOwnedRecordDbRecord> tstITestDBContext.T015ChildOwnedRecords => T015ChildOwnedRecords;
	IEnumerable<tstIT015ChildOwnedRecordDbRecord> tstITestDBContext.T015ChildOwnedRecordsLocal => T015ChildOwnedRecordsLocal;
	IInMemoryDBSet<tstIT015ChildOwnedRecordDbRecord, tstT015ChildOwnedRecord> tstITestDBContext.T015ChildOwnedRecordsInMemory => null;
	IQueryable<tstIT015ParentOrderedRecordDbRecord> tstITestDBContext.T015ParentOrderedRecords => T015ParentOrderedRecords;
	IEnumerable<tstIT015ParentOrderedRecordDbRecord> tstITestDBContext.T015ParentOrderedRecordsLocal => T015ParentOrderedRecordsLocal;
	IInMemoryDBSet<tstIT015ParentOrderedRecordDbRecord, tstT015ParentOrderedRecord> tstITestDBContext.T015ParentOrderedRecordsInMemory => null;
	IQueryable<tstIT016CompositeParentRecordDbRecord> tstITestDBContext.T016CompositeParentRecords => T016CompositeParentRecords;
	IEnumerable<tstIT016CompositeParentRecordDbRecord> tstITestDBContext.T016CompositeParentRecordsLocal => T016CompositeParentRecordsLocal;
	IInMemoryDBSet<tstIT016CompositeParentRecordDbRecord, tstT016CompositeParentRecord> tstITestDBContext.T016CompositeParentRecordsInMemory => null;
	IQueryable<tstIRawDbEntity> tstITestDBContext.RawsWithComposites => RawsWithComposites;
	IQueryable<tstIRequiredSharedRefDbEntity> tstITestDBContext.RequiredSharedRefsWithComposites => RequiredSharedRefsWithComposites;
	IQueryable<tstIOptionalSharedRefDbEntity> tstITestDBContext.OptionalSharedRefsWithComposites => OptionalSharedRefsWithComposites;
	IQueryable<tstICompositeRefParentDbEntity> tstITestDBContext.CompositeRefParentsWithComposites => CompositeRefParentsWithComposites;
	IQueryable<tstIOptionalCompositeRefParentDbEntity> tstITestDBContext.OptionalCompositeRefParentsWithComposites => OptionalCompositeRefParentsWithComposites;
	IQueryable<tstIOwnerContainerDbEntity> tstITestDBContext.OwnerContainersWithComposites => OwnerContainersWithComposites;
	IQueryable<tstICompositesContainerDbEntity> tstITestDBContext.CompositesContainersWithComposites => CompositesContainersWithComposites;
	IQueryable<tstISharedContainerDbEntity> tstITestDBContext.SharedContainersWithComposites => SharedContainersWithComposites;
	IQueryable<tstIMultipleSharedContainerDbEntity> tstITestDBContext.MultipleSharedContainersWithComposites => MultipleSharedContainersWithComposites;
	IQueryable<tstIMixedContainerDbEntity> tstITestDBContext.MixedContainersWithComposites => MixedContainersWithComposites;
	IQueryable<tstIMultipleCompositeRefDbEntity> tstITestDBContext.MultipleCompositeRefsWithComposites => MultipleCompositeRefsWithComposites;
	IQueryable<tstIMultipleSharedRefDbEntity> tstITestDBContext.MultipleSharedRefsWithComposites => MultipleSharedRefsWithComposites;
	IQueryable<tstINestedCompositeRootDbEntity> tstITestDBContext.NestedCompositeRootsWithComposites => NestedCompositeRootsWithComposites;
	IQueryable<tstIChildDbEntity> tstITestDBContext.ChildrenWithComposites => ChildrenWithComposites;
	IQueryable<tstIParentDbEntity> tstITestDBContext.ParentsWithComposites => ParentsWithComposites;
	IQueryable<tstIT001ChildDbEntity> tstITestDBContext.T001ChildrenWithComposites => T001ChildrenWithComposites;
	IQueryable<tstIT001ParentOwnerDbEntity> tstITestDBContext.T001ParentOwnersWithComposites => T001ParentOwnersWithComposites;
	IQueryable<tstIParentWithSharedListDbEntity> tstITestDBContext.ParentWithSharedListsWithComposites => ParentWithSharedListsWithComposites;
	IQueryable<tstIT002ChildDbEntity> tstITestDBContext.T002ChildrenWithComposites => T002ChildrenWithComposites;
	IQueryable<tstIT002ParentOwnerDbEntity> tstITestDBContext.T002ParentOwnersWithComposites => T002ParentOwnersWithComposites;
	IQueryable<tstIT002ChildHolderDbEntity> tstITestDBContext.T002ChildHoldersWithComposites => T002ChildHoldersWithComposites;
	IQueryable<tstIT003ChildDbEntity> tstITestDBContext.T003ChildrenWithComposites => T003ChildrenWithComposites;
	IQueryable<tstIT003ParentOwnerDbEntity> tstITestDBContext.T003ParentOwnersWithComposites => T003ParentOwnersWithComposites;
	IQueryable<tstIT003ChildHolderDbEntity> tstITestDBContext.T003ChildHoldersWithComposites => T003ChildHoldersWithComposites;
	IQueryable<tstIT004RecursiveLinkSetDbEntity> tstITestDBContext.T004RecursiveLinkSetsWithComposites => T004RecursiveLinkSetsWithComposites;
	IQueryable<tstIT005RecursiveLinkListDbEntity> tstITestDBContext.T005RecursiveLinkListsWithComposites => T005RecursiveLinkListsWithComposites;
	IQueryable<tstIT006PerfMaxQueryItemDbEntity> tstITestDBContext.T006PerfMaxQueryItemsWithComposites => T006PerfMaxQueryItemsWithComposites;
	IQueryable<tstIT006PerfMaxQueryValueDbEntity> tstITestDBContext.T006PerfMaxQueryValuesWithComposites => T006PerfMaxQueryValuesWithComposites;
	IQueryable<tstIT007LeafDbEntity> tstITestDBContext.T007LeavesWithComposites => T007LeavesWithComposites;
	IQueryable<tstIT007RootDbEntity> tstITestDBContext.T007RootsWithComposites => T007RootsWithComposites;
	IQueryable<tstIT008ParentDbEntity> tstITestDBContext.T008ParentsWithComposites => T008ParentsWithComposites;
	IQueryable<tstIT009PrincipalDbEntity> tstITestDBContext.T009PrincipalsWithComposites => T009PrincipalsWithComposites;
	IQueryable<tstIT009UserDbEntity> tstITestDBContext.T009UsersWithComposites => T009UsersWithComposites;
	IQueryable<tstIT010CompositeRefParentDbEntity> tstITestDBContext.T010CompositeRefParentsWithComposites => T010CompositeRefParentsWithComposites;
	IQueryable<tstIT011CompositeRefParentDbEntity> tstITestDBContext.T011CompositeRefParentsWithComposites => T011CompositeRefParentsWithComposites;
	IQueryable<tstIT012CompositeRefParentDbEntity> tstITestDBContext.T012CompositeRefParentsWithComposites => T012CompositeRefParentsWithComposites;
	IQueryable<tstIT013CompositeRefParentDbEntity> tstITestDBContext.T013CompositeRefParentsWithComposites => T013CompositeRefParentsWithComposites;
	IQueryable<tstIT014AutoCreateValueDbEntity> tstITestDBContext.T014AutoCreateValuesWithComposites => T014AutoCreateValuesWithComposites;
	IQueryable<tstIT015ParentRecordDbRecord> tstITestDBContext.T015ParentRecordsWithComposites => T015ParentRecordsWithComposites;
	IQueryable<tstIT015ChildL1RecordDbRecord> tstITestDBContext.T015ChildL1RecordsWithComposites => T015ChildL1RecordsWithComposites;
	IQueryable<tstIT015ChildL2RecordDbRecord> tstITestDBContext.T015ChildL2RecordsWithComposites => T015ChildL2RecordsWithComposites;
	IQueryable<tstIT015ChildOwnedRecordDbRecord> tstITestDBContext.T015ChildOwnedRecordsWithComposites => T015ChildOwnedRecordsWithComposites;
	IQueryable<tstIT015ParentOrderedRecordDbRecord> tstITestDBContext.T015ParentOrderedRecordsWithComposites => T015ParentOrderedRecordsWithComposites;
	IQueryable<tstIT016CompositeParentRecordDbRecord> tstITestDBContext.T016CompositeParentRecordsWithComposites => T016CompositeParentRecordsWithComposites;
}
public partial class tstT016CompositeChildRecordDbRecord : tstIT016CompositeChildRecordDbRecord
{
	// No navigation properties for composite entity
}
public partial class tstChildDbEntity : tstIChildDbEntity
{
	tstIParentDbEntity tstIChildDbEntity.SecondParent => SecondParent;
	// No navigation properties for composite entity
}
public partial class tstCompositeChildDbEntity : tstICompositeChildDbEntity
{
	// No navigation properties for composite entity
}
public partial class tstCompositeRefParentDbEntity : tstICompositeRefParentDbEntity
{
	tstICompositeChildDbEntity tstICompositeRefParentDbEntity.Composite => Composite;
	// No navigation properties for composite entity
}
public partial class tstCompositesContainerDbEntity : tstICompositesContainerDbEntity
{
	IEnumerable<tstICompositeChildDbEntity> tstICompositesContainerDbEntity.Composites => Composites;
	// No navigation properties for composite entity
}
public partial class tstMixedContainer_tstRaw_Owneds : tstIMixedContainer_tstRaw_OwnedsDbEntity
{
	tstIMixedContainerDbEntity tstIMixedContainer_tstRaw_OwnedsDbEntity.Parent => Parent;
	tstIRawDbEntity tstIMixedContainer_tstRaw_OwnedsDbEntity.Child => Child;
}
public partial class tstMixedContainer_tstRaw_Shareds : tstIMixedContainer_tstRaw_SharedsDbEntity
{
	tstIMixedContainerDbEntity tstIMixedContainer_tstRaw_SharedsDbEntity.Parent => Parent;
	tstIRawDbEntity tstIMixedContainer_tstRaw_SharedsDbEntity.Child => Child;
}
public partial class tstMixedContainerDbEntity : tstIMixedContainerDbEntity
{
	IEnumerable<tstIMixedContainer_tstRaw_OwnedsDbEntity> tstIMixedContainerDbEntity.Owneds => Owneds;
	IEnumerable<tstIMixedContainer_tstRaw_SharedsDbEntity> tstIMixedContainerDbEntity.Shareds => Shareds;
	// No navigation properties for composite entity
}
public partial class tstMultipleCompositeRefDbEntity : tstIMultipleCompositeRefDbEntity
{
	tstICompositeChildDbEntity tstIMultipleCompositeRefDbEntity.Composite => Composite;
	tstICompositeChildDbEntity tstIMultipleCompositeRefDbEntity.OptionalComposite => OptionalComposite;
	// No navigation properties for composite entity
}
public partial class tstMultipleSharedContainer_tstRaw_FirstShareds : tstIMultipleSharedContainer_tstRaw_FirstSharedsDbEntity
{
	tstIMultipleSharedContainerDbEntity tstIMultipleSharedContainer_tstRaw_FirstSharedsDbEntity.Parent => Parent;
	tstIRawDbEntity tstIMultipleSharedContainer_tstRaw_FirstSharedsDbEntity.Child => Child;
}
public partial class tstMultipleSharedContainer_tstRaw_SecondShareds : tstIMultipleSharedContainer_tstRaw_SecondSharedsDbEntity
{
	tstIMultipleSharedContainerDbEntity tstIMultipleSharedContainer_tstRaw_SecondSharedsDbEntity.Parent => Parent;
	tstIRawDbEntity tstIMultipleSharedContainer_tstRaw_SecondSharedsDbEntity.Child => Child;
}
public partial class tstMultipleSharedContainerDbEntity : tstIMultipleSharedContainerDbEntity
{
	IEnumerable<tstIMultipleSharedContainer_tstRaw_FirstSharedsDbEntity> tstIMultipleSharedContainerDbEntity.FirstShareds => FirstShareds;
	IEnumerable<tstIMultipleSharedContainer_tstRaw_SecondSharedsDbEntity> tstIMultipleSharedContainerDbEntity.SecondShareds => SecondShareds;
	// No navigation properties for composite entity
}
public partial class tstMultipleSharedRefDbEntity : tstIMultipleSharedRefDbEntity
{
	tstIRawDbEntity tstIMultipleSharedRefDbEntity.Raw => Raw;
	tstIRawDbEntity tstIMultipleSharedRefDbEntity.OptionalRaw => OptionalRaw;
	// No navigation properties for composite entity
}
public partial class tstNestedCompositeRoot_tstRaw_RawLists : tstINestedCompositeRoot_tstRaw_RawListsDbEntity
{
	tstINestedCompositeRootDbEntity tstINestedCompositeRoot_tstRaw_RawListsDbEntity.Parent => Parent;
	tstIRawDbEntity tstINestedCompositeRoot_tstRaw_RawListsDbEntity.Child => Child;
}
public partial class tstNestedCompositeRootDbEntity : tstINestedCompositeRootDbEntity
{
	tstICompositeChildDbEntity tstINestedCompositeRootDbEntity.Composite => Composite;
	tstICompositeChildDbEntity tstINestedCompositeRootDbEntity.OptionalComposite => OptionalComposite;
	tstINestedCompositesDbEntity tstINestedCompositeRootDbEntity.Nested => Nested;
	tstIRawDbEntity tstINestedCompositeRootDbEntity.OptionalRaw => OptionalRaw;
	IEnumerable<tstINestedCompositeRoot_tstRaw_RawListsDbEntity> tstINestedCompositeRootDbEntity.RawLists => RawLists;
	// No navigation properties for composite entity
}
public partial class tstNestedCompositesDbEntity : tstINestedCompositesDbEntity
{
	tstICompositeChildDbEntity tstINestedCompositesDbEntity.Composite => Composite;
	IEnumerable<tstICompositeChildDbEntity> tstINestedCompositesDbEntity.Children => Children;
	// No navigation properties for composite entity
}
public partial class tstOptionalCompositeRefParentDbEntity : tstIOptionalCompositeRefParentDbEntity
{
	tstICompositeChildDbEntity tstIOptionalCompositeRefParentDbEntity.Composite => Composite;
	// No navigation properties for composite entity
}
public partial class tstOptionalSharedRefDbEntity : tstIOptionalSharedRefDbEntity
{
	tstIRawDbEntity tstIOptionalSharedRefDbEntity.Raw => Raw;
	// No navigation properties for composite entity
}
public partial class tstOwnerContainer_tstRaw_Raws : tstIOwnerContainer_tstRaw_RawsDbEntity
{
	tstIOwnerContainerDbEntity tstIOwnerContainer_tstRaw_RawsDbEntity.Parent => Parent;
	tstIRawDbEntity tstIOwnerContainer_tstRaw_RawsDbEntity.Child => Child;
}
public partial class tstOwnerContainerDbEntity : tstIOwnerContainerDbEntity
{
	IEnumerable<tstIOwnerContainer_tstRaw_RawsDbEntity> tstIOwnerContainerDbEntity.Raws => Raws;
	// No navigation properties for composite entity
}
public partial class tstParent_tstChild_Children : tstIParent_tstChild_ChildrenDbEntity
{
	tstIParentDbEntity tstIParent_tstChild_ChildrenDbEntity.Parent => Parent;
	tstIChildDbEntity tstIParent_tstChild_ChildrenDbEntity.Child => Child;
}
public partial class tstParentDbEntity : tstIParentDbEntity
{
	IEnumerable<tstIParent_tstChild_ChildrenDbEntity> tstIParentDbEntity.Children => Children;
	// No navigation properties for composite entity
}
public partial class tstParentWithSharedList_tstRaw_RawLists : tstIParentWithSharedList_tstRaw_RawListsDbEntity
{
	tstIParentWithSharedListDbEntity tstIParentWithSharedList_tstRaw_RawListsDbEntity.Parent => Parent;
	tstIRawDbEntity tstIParentWithSharedList_tstRaw_RawListsDbEntity.Child => Child;
}
public partial class tstParentWithSharedListDbEntity : tstIParentWithSharedListDbEntity
{
	IEnumerable<tstIParentWithSharedList_tstRaw_RawListsDbEntity> tstIParentWithSharedListDbEntity.RawLists => RawLists;
	// No navigation properties for composite entity
}
public partial class tstRawDbEntity : tstIRawDbEntity
{
	// No navigation properties for composite entity
}
public partial class tstRequiredSharedRefDbEntity : tstIRequiredSharedRefDbEntity
{
	tstIRawDbEntity tstIRequiredSharedRefDbEntity.Raw => Raw;
	// No navigation properties for composite entity
}
public partial class tstSharedContainer_tstRaw_Shareds : tstISharedContainer_tstRaw_SharedsDbEntity
{
	tstISharedContainerDbEntity tstISharedContainer_tstRaw_SharedsDbEntity.Parent => Parent;
	tstIRawDbEntity tstISharedContainer_tstRaw_SharedsDbEntity.Child => Child;
}
public partial class tstSharedContainerDbEntity : tstISharedContainerDbEntity
{
	IEnumerable<tstISharedContainer_tstRaw_SharedsDbEntity> tstISharedContainerDbEntity.Shareds => Shareds;
	// No navigation properties for composite entity
}
public partial class tstT001ChildDbEntity : tstIT001ChildDbEntity
{
	tstICompositeChildDbEntity tstIT001ChildDbEntity.CompositeChild => CompositeChild;
	// No navigation properties for composite entity
}
public partial class tstT001ParentOwner_tstT001Child_T001Children : tstIT001ParentOwner_tstT001Child_T001ChildrenDbEntity
{
	tstIT001ParentOwnerDbEntity tstIT001ParentOwner_tstT001Child_T001ChildrenDbEntity.Parent => Parent;
	tstIT001ChildDbEntity tstIT001ParentOwner_tstT001Child_T001ChildrenDbEntity.Child => Child;
}
public partial class tstT001ParentOwnerDbEntity : tstIT001ParentOwnerDbEntity
{
	IEnumerable<tstIT001ParentOwner_tstT001Child_T001ChildrenDbEntity> tstIT001ParentOwnerDbEntity.T001Children => T001Children;
	// No navigation properties for composite entity
}
public partial class tstT002ChildDbEntity : tstIT002ChildDbEntity
{
	// No navigation properties for composite entity
}
public partial class tstT002ChildHolderDbEntity : tstIT002ChildHolderDbEntity
{
	tstIT002ChildDbEntity tstIT002ChildHolderDbEntity.T002Child => T002Child;
	// No navigation properties for composite entity
}
public partial class tstT002ParentOwner_tstT002Child_T002Children : tstIT002ParentOwner_tstT002Child_T002ChildrenDbEntity
{
	tstIT002ParentOwnerDbEntity tstIT002ParentOwner_tstT002Child_T002ChildrenDbEntity.Parent => Parent;
	tstIT002ChildDbEntity tstIT002ParentOwner_tstT002Child_T002ChildrenDbEntity.Child => Child;
}
public partial class tstT002ParentOwnerDbEntity : tstIT002ParentOwnerDbEntity
{
	IEnumerable<tstIT002ParentOwner_tstT002Child_T002ChildrenDbEntity> tstIT002ParentOwnerDbEntity.T002Children => T002Children;
	// No navigation properties for composite entity
}
public partial class tstT003ChildDbEntity : tstIT003ChildDbEntity
{
	// No navigation properties for composite entity
}
public partial class tstT003ChildHolderDbEntity : tstIT003ChildHolderDbEntity
{
	tstIT003ChildDbEntity tstIT003ChildHolderDbEntity.T003Child => T003Child;
	// No navigation properties for composite entity
}
public partial class tstT003ParentOwner_tstT003Child_T003Children : tstIT003ParentOwner_tstT003Child_T003ChildrenDbEntity
{
	tstIT003ParentOwnerDbEntity tstIT003ParentOwner_tstT003Child_T003ChildrenDbEntity.Parent => Parent;
	tstIT003ChildDbEntity tstIT003ParentOwner_tstT003Child_T003ChildrenDbEntity.Child => Child;
}
public partial class tstT003ParentOwnerDbEntity : tstIT003ParentOwnerDbEntity
{
	IEnumerable<tstIT003ParentOwner_tstT003Child_T003ChildrenDbEntity> tstIT003ParentOwnerDbEntity.T003Children => T003Children;
	// No navigation properties for composite entity
}
public partial class tstT004RecursiveLinkSet_tstT004RecursiveLinkSet_RecursiveLinks : tstIT004RecursiveLinkSet_tstT004RecursiveLinkSet_RecursiveLinksDbEntity
{
	tstIT004RecursiveLinkSetDbEntity tstIT004RecursiveLinkSet_tstT004RecursiveLinkSet_RecursiveLinksDbEntity.Parent => Parent;
	tstIT004RecursiveLinkSetDbEntity tstIT004RecursiveLinkSet_tstT004RecursiveLinkSet_RecursiveLinksDbEntity.Child => Child;
}
public partial class tstT004RecursiveLinkSetDbEntity : tstIT004RecursiveLinkSetDbEntity
{
	IEnumerable<tstIT004RecursiveLinkSet_tstT004RecursiveLinkSet_RecursiveLinksDbEntity> tstIT004RecursiveLinkSetDbEntity.RecursiveLinks => RecursiveLinks;
	// No navigation properties for composite entity
}
public partial class tstT005RecursiveLinkList_tstT005RecursiveLinkList_RecursiveLinks : tstIT005RecursiveLinkList_tstT005RecursiveLinkList_RecursiveLinksDbEntity
{
	tstIT005RecursiveLinkListDbEntity tstIT005RecursiveLinkList_tstT005RecursiveLinkList_RecursiveLinksDbEntity.Parent => Parent;
	tstIT005RecursiveLinkListDbEntity tstIT005RecursiveLinkList_tstT005RecursiveLinkList_RecursiveLinksDbEntity.Child => Child;
}
public partial class tstT005RecursiveLinkListDbEntity : tstIT005RecursiveLinkListDbEntity
{
	IEnumerable<tstIT005RecursiveLinkList_tstT005RecursiveLinkList_RecursiveLinksDbEntity> tstIT005RecursiveLinkListDbEntity.RecursiveLinks => RecursiveLinks;
	// No navigation properties for composite entity
}
public partial class tstT006PerfMaxQueryItemDbEntity : tstIT006PerfMaxQueryItemDbEntity
{
	// No navigation properties for composite entity
}
public partial class tstT006PerfMaxQueryValueDbEntity : tstIT006PerfMaxQueryValueDbEntity
{
	// No navigation properties for composite entity
}
public partial class tstT007Leaf_tstT007Leaf_T007Leaves : tstIT007Leaf_tstT007Leaf_T007LeavesDbEntity
{
	tstIT007LeafDbEntity tstIT007Leaf_tstT007Leaf_T007LeavesDbEntity.Parent => Parent;
	tstIT007LeafDbEntity tstIT007Leaf_tstT007Leaf_T007LeavesDbEntity.Child => Child;
}
public partial class tstT007LeafDbEntity : tstIT007LeafDbEntity
{
	IEnumerable<tstIT007Leaf_tstT007Leaf_T007LeavesDbEntity> tstIT007LeafDbEntity.T007Leaves => T007Leaves;
	// No navigation properties for composite entity
}
public partial class tstT007Root_tstT007Leaf_T007Leaves : tstIT007Root_tstT007Leaf_T007LeavesDbEntity
{
	tstIT007RootDbEntity tstIT007Root_tstT007Leaf_T007LeavesDbEntity.Parent => Parent;
	tstIT007LeafDbEntity tstIT007Root_tstT007Leaf_T007LeavesDbEntity.Child => Child;
}
public partial class tstT007RootDbEntity : tstIT007RootDbEntity
{
	IEnumerable<tstIT007Root_tstT007Leaf_T007LeavesDbEntity> tstIT007RootDbEntity.T007Leaves => T007Leaves;
	// No navigation properties for composite entity
}
public partial class tstT008ParentDbEntity : tstIT008ParentDbEntity
{
	tstICompositeChildDbEntity tstIT008ParentDbEntity.Child => Child;
	tstIRawDbEntity tstIT008ParentDbEntity.Raw => Raw;
	// No navigation properties for composite entity
}
public partial class tstT009CompositeDbEntity : tstIT009CompositeDbEntity
{
	// No navigation properties for composite entity
}
public partial class tstT009PrincipalDbEntity : tstIT009PrincipalDbEntity
{
	tstIT009CompositeDbEntity tstIT009PrincipalDbEntity.Composite => Composite;
	IEnumerable<tstIT009CompositeDbEntity> tstIT009PrincipalDbEntity.T009Composites => T009Composites;
	// No navigation properties for composite entity
}
public partial class tstT009UserDbEntity : tstIT009UserDbEntity
{
	tstIT009PrincipalDbEntity tstIT009UserDbEntity.Principal => Principal;
	// No navigation properties for composite entity
}
public partial class tstT010CompositeRefParentDbEntity : tstIT010CompositeRefParentDbEntity
{
	IEnumerable<tstIT010CompositeRefChildDbEntity> tstIT010CompositeRefParentDbEntity.T010CompositeRefChildren => T010CompositeRefChildren;
	tstIT010CompositeRefChildDbEntity tstIT010CompositeRefParentDbEntity.T010CompositeRefChild => T010CompositeRefChild;
	// No navigation properties for composite entity
}
public partial class tstT011CompositeRefParentDbEntity : tstIT011CompositeRefParentDbEntity
{
	tstIT011CompositeRefParentContainerDbEntity tstIT011CompositeRefParentDbEntity.Container => Container;
	// No navigation properties for composite entity
}
public partial class tstT011CompositeRefParentContainerDbEntity : tstIT011CompositeRefParentContainerDbEntity
{
	IEnumerable<tstICompositeChildDbEntity> tstIT011CompositeRefParentContainerDbEntity.CompositeChildren => CompositeChildren;
	tstICompositeChildDbEntity tstIT011CompositeRefParentContainerDbEntity.CompositeChild => CompositeChild;
	// No navigation properties for composite entity
}
public partial class tstT012CompositeRefParentDbEntity : tstIT012CompositeRefParentDbEntity
{
	tstIT012CompositeRefParentContainerDbEntity tstIT012CompositeRefParentDbEntity.Container => Container;
	// No navigation properties for composite entity
}
public partial class tstT012CompositeRefParentContainerDbEntity : tstIT012CompositeRefParentContainerDbEntity
{
	tstICompositeChildDbEntity tstIT012CompositeRefParentContainerDbEntity.CompositeChild => CompositeChild;
	// No navigation properties for composite entity
}
public partial class tstT013CompositeRefParentDbEntity : tstIT013CompositeRefParentDbEntity
{
	tstIT013CompositeRefParentContainerDbEntity tstIT013CompositeRefParentDbEntity.Container => Container;
	// No navigation properties for composite entity
}
public partial class tstT013CompositeRefParentContainerDbEntity : tstIT013CompositeRefParentContainerDbEntity
{
	IEnumerable<tstICompositeChildDbEntity> tstIT013CompositeRefParentContainerDbEntity.CompositeChildren => CompositeChildren;
	// No navigation properties for composite entity
}
public partial class tstT014AutoCreateValueDbEntity : tstIT014AutoCreateValueDbEntity
{
	tstIRawDbEntity tstIT014AutoCreateValueDbEntity.Reference => Reference;
	// No navigation properties for composite entity
}
public partial class tstT015ChildL1Record_tstT015ChildL2Record_Children : tstIT015ChildL1Record_tstT015ChildL2Record_ChildrenDbEntity
{
	tstIT015ChildL1RecordDbRecord tstIT015ChildL1Record_tstT015ChildL2Record_ChildrenDbEntity.Parent => Parent;
	tstIT015ChildL2RecordDbRecord tstIT015ChildL1Record_tstT015ChildL2Record_ChildrenDbEntity.Child => Child;
}
public partial class tstT015ChildL1RecordDbRecord : tstIT015ChildL1RecordDbRecord
{
	tstIT015ChildL2RecordDbRecord tstIT015ChildL1RecordDbRecord.OptionalChild => OptionalChild;
	tstIT015ChildL2RecordDbRecord tstIT015ChildL1RecordDbRecord.RequiredChild => RequiredChild;
	IEnumerable<tstIT015ChildL1Record_tstT015ChildL2Record_ChildrenDbEntity> tstIT015ChildL1RecordDbRecord.Children => Children;
	// No navigation properties for composite entity
}
public partial class tstT015ChildL2RecordDbRecord : tstIT015ChildL2RecordDbRecord
{
	// No navigation properties for composite entity
}
public partial class tstT015ChildOwnedRecordDbRecord : tstIT015ChildOwnedRecordDbRecord
{
	// No navigation properties for composite entity
}
public partial class tstT015CompositeChildDbRecord : tstIT015CompositeChildDbRecord
{
	// No navigation properties for composite entity
}
public partial class tstT015ParentOrderedRecord_tstT015ChildOwnedRecord_OrderedOwnedChildren : tstIT015ParentOrderedRecord_tstT015ChildOwnedRecord_OrderedOwnedChildrenDbEntity
{
	tstIT015ParentOrderedRecordDbRecord tstIT015ParentOrderedRecord_tstT015ChildOwnedRecord_OrderedOwnedChildrenDbEntity.Parent => Parent;
	tstIT015ChildOwnedRecordDbRecord tstIT015ParentOrderedRecord_tstT015ChildOwnedRecord_OrderedOwnedChildrenDbEntity.Child => Child;
}
public partial class tstT015ParentOrderedRecord_tstT015ChildL1Record_OrderedChildren : tstIT015ParentOrderedRecord_tstT015ChildL1Record_OrderedChildrenDbEntity
{
	tstIT015ParentOrderedRecordDbRecord tstIT015ParentOrderedRecord_tstT015ChildL1Record_OrderedChildrenDbEntity.Parent => Parent;
	tstIT015ChildL1RecordDbRecord tstIT015ParentOrderedRecord_tstT015ChildL1Record_OrderedChildrenDbEntity.Child => Child;
}
public partial class tstT015ParentOrderedRecordDbRecord : tstIT015ParentOrderedRecordDbRecord
{
	IEnumerable<tstIT015ParentOrderedRecord_tstT015ChildOwnedRecord_OrderedOwnedChildrenDbEntity> tstIT015ParentOrderedRecordDbRecord.OrderedOwnedChildren => OrderedOwnedChildren;
	IEnumerable<tstIT015ParentOrderedRecord_tstT015ChildL1Record_OrderedChildrenDbEntity> tstIT015ParentOrderedRecordDbRecord.OrderedChildren => OrderedChildren;
	IEnumerable<tstIT015CompositeChildDbRecord> tstIT015ParentOrderedRecordDbRecord.CompositeOderedChildren => CompositeOderedChildren;
	// No navigation properties for composite entity
}
public partial class tstT015ParentRecord_tstT015ChildL1Record_Children : tstIT015ParentRecord_tstT015ChildL1Record_ChildrenDbEntity
{
	tstIT015ParentRecordDbRecord tstIT015ParentRecord_tstT015ChildL1Record_ChildrenDbEntity.Parent => Parent;
	tstIT015ChildL1RecordDbRecord tstIT015ParentRecord_tstT015ChildL1Record_ChildrenDbEntity.Child => Child;
}
public partial class tstT015ParentRecordDbRecord : tstIT015ParentRecordDbRecord
{
	tstIT015ChildL1RecordDbRecord tstIT015ParentRecordDbRecord.OptionalChild => OptionalChild;
	tstIT015ChildL1RecordDbRecord tstIT015ParentRecordDbRecord.RequiredChild => RequiredChild;
	IEnumerable<tstIT015ParentRecord_tstT015ChildL1Record_ChildrenDbEntity> tstIT015ParentRecordDbRecord.Children => Children;
	tstIT015CompositeChildDbRecord tstIT015ParentRecordDbRecord.OptionalCompositeChild => OptionalCompositeChild;
	tstIT015CompositeChildDbRecord tstIT015ParentRecordDbRecord.RequiredCompositeChild => RequiredCompositeChild;
	IEnumerable<tstIT015CompositeChildDbRecord> tstIT015ParentRecordDbRecord.CompositeChildren => CompositeChildren;
	// No navigation properties for composite entity
}
public partial class tstT016CompositeParentRecordDbRecord : tstIT016CompositeParentRecordDbRecord
{
	IEnumerable<tstIT016CompositeChildRecordDbRecord> tstIT016CompositeParentRecordDbRecord.Children => Children;
	// No navigation properties for composite entity
}
public partial class tstT010CompositeRefChildDbEntity : tstIT010CompositeRefChildDbEntity
{
	tstIRawDbEntity tstIT010CompositeRefChildDbEntity.Raw => Raw;
	// No navigation properties for composite entity
}
}
#pragma warning restore CS0612 // Type or member is obsolete
#pragma warning restore CS0105 // Using directive appeared previously in this namespace
#pragma warning restore CS1998 // Async method lacks 'await' operators and will run synchronously
#pragma warning restore IDE0028 // Collection Initialization
#pragma warning restore IDE0017 // Object Initialization
#pragma warning restore IDE1006 // Naming Styles
